### ISSUE TITLE
Button stays in focus styling after pressed

### ISSUE THREAD

**Issue by nicolehli** [shanicem/cmd-f-2019#2]
The load example button seems to be "stuck" in focus mode after pressed. This is due to the type=button attribute, but without type=button then the <button> will reload the page upon pressed and have the stuck of focus style issue. 

Related:
https://github.com/react-bootstrap/react-bootstrap/issues/1300
https://stackoverflow.com/questions/1878264/how-do-i-make-an-html-button-not-reload-the-page

**Comment by nicolehli** [comment]
After some investigation, seems like issue is with Chrome browser. Closing ticket.

**Comment by nicolehli** [comment]
The focus is for accessability. Using css outline: none and using !important did solve the issue. The focus outline is a part of the class btn. This is a note to myself.

**Comment by fuzzbomb** [comment]
It is **normal** behaviour for `<button type="button">` to stay focused after pressing it. It doesn't have a default click behaviour.

Removing the `type="button"` attribute means it is equivalent to a `<button type="submit">` because that's the default type. In this case, the button does have a default behaviour: submission of the associated form. This often results in a reload of the page.

> Using css outline: none and using !important did solve the issue. 

That just stops the focus from being _visually_ displayed. It doesn't change the focus state itself.
